volumes:
  kagome-dist:

services:
  build-kagome:
    build:
      context: .
    volumes:
      - kagome-dist:/app/libkagome/bin
      - ./Makefile:/app/Makefile:ro
      - ./libkagome/go_wrapper:/app/libkagome/go_wrapper:ro
      - ./libkagome/c_wrapper:/app/libkagome/c_wrapper:ro
    working_dir: /app
    entrypoint: ["make", "build"]

  test-python:
    image: python:latest
    volumes:
      - kagome-dist:/app/libkagome/bin:ro
      - ./Makefile:/app/Makefile:ro
      - ./libkagome/python_wrapper:/app/libkagome/python_wrapper:ro
    working_dir: /app
    entrypoint: ["make", "test-python"]
    depends_on:
      build-kagome:
        condition: service_completed_successfully
